# Reservation 등록
POST {{host}}/api/v1/reservations
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tid" : "12311471248182471",
  "rooftopId" :  1,
  "startDate" : "2022-10-02",
  "endDate" : "2022-09-01",
  "startTime" : "10:00:00",
  "endTime" : "18:00:00",
  "adultCount" : 2,
  "kidCount" : 0,
  "petCount" : 0,
  "totalCount" : 2,
  "paymentType" : "KAKAO_PAY",
  "totalPrice" : 120000,
  "contents" : ["0", "1"],
  "prices" : [15000, 20000],
  "counts" : [0, 1]
}

###
# Reservation 조회
GET {{host}}/api/v1/reservations/5
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
# Reservation 삭제
DELETE {{host}}/api/v1/reservations/9
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# Reservation 변경
POST {{host}}/api/v1/reservations/7
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status" : "PAYMENT_COMPLETED"
}

###
# 내 예약 내역 확인
GET {{host}}/api/v1/reservations?date=2022-10-02
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
# Reservation Waiting 조회
GET {{host}}/api/v1/reservations/members/waiting
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# Reservation Completed 조회
GET {{host}}/api/v1/reservations/members/completed
Content-Type: application/json
Authorization: Bearer {{accessToken}}