# 로그인
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
client.global.set("accessToken", response.body.data.tokenDto.accessToken);
 %}

###
# Rooftop 생성 - formData
POST {{host}}/api/v1/rooftops/green
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="width"

111
--boundary
Content-Disposition: form-data; name="county"

test
--boundary
Content-Disposition: form-data; name="city"

test
--boundary
Content-Disposition: form-data; name="detail"

test
--boundary
Content-Disposition: form-data; name="rooftopType"

G
--boundary
Content-Disposition: form-data; name="startTime"

12:00:00
--boundary
Content-Disposition: form-data; name="endTime"

13:00:00
--boundary
Content-Disposition: form-data; name="adultCount"

5
--boundary
Content-Disposition: form-data; name="totalPrice"

120000
--boundary--
Content-Disposition: form-data; name="optionContent"

hihi
--boundary--
Content-Disposition: form-data; name="optionPrice"

10000
--boundary--
Content-Disposition: form-data; name="optionCount"

3
--boundary--
Content-Disposition: form-data; name="optionContent"

hihi2
--boundary--
Content-Disposition: form-data; name="optionPrice"

20000
--boundary--
Content-Disposition: form-data; name="optionCount"

0


###
# Rooftop Seach Cond(NG) 조회
GET {{host}}/api/v1/rooftops/search?page=0&type=NG&deadLineType=3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Rooftop Seach Cond(G) 조회
GET {{host}}/api/v1/rooftops/search?page=0&type=G
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# 본인 RooftopReview 조회
GET {{host}}/api/v1/rooftops/reviews?page=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Rooftop Review 생성
POST {{host}}/api/v1/rooftops/reviews/13
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "grade": 3,
  "content": "test 용도2222"
}

###
# Rooftop Review 삭제
DELETE {{host}}/api/v1/rooftops/reviews/1/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Rooftop Detail 조회
GET {{host}}/api/v1/rooftops/detail/13
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# 나의 Rooftop 조회
GET {{host}}/api/v1/rooftops?page=0&size=1000000
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Rooftop 수정
PATCH {{host}}/api/v1/rooftops/detail/13
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="adultCount"

3
--boundary
Content-Disposition: form-data; name="petCount"

2
--boundary
Content-Disposition: form-data; name="endTime"

14:00:00

###
# Rooftop Option 수정
POST {{host}}/api/v1/rooftops/detail/option/13
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary--
Content-Disposition: form-data; name="optionContent"

bye2
--boundary--
Content-Disposition: form-data; name="optionPrice"

1234
--boundary--
Content-Disposition: form-data; name="optionCount"

7

