# 로그인
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
client.global.set("accessToken", response.body.data.tokenDto.accessToken);
 %}

###
# Rooftop 생성 - formData
POST {{host}}/api/v1/rooftops/green
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="normalFile"; filename="usecase1.png"

< /Users/yc/Documents/usecase/usecase1.png
--boundary
Content-Disposition: form-data; name="structureFile"; filename="usecase2.png"

< /Users/yc/Documents/usecase/usecase2.png
--boundary
Content-Disposition: form-data; name="mainFile"; filename="usecase2.png"

< /Users/yc/Documents/usecase/usecase2.png
--boundary
Content-Disposition: form-data; name="width"

24
--boundary
Content-Disposition: form-data; name="county"

testtset1
--boundary
Content-Disposition: form-data; name="city"

testtset1
--boundary
Content-Disposition: form-data; name="detail"

testtset1
--boundary
Content-Disposition: form-data; name="rooftopType"

NG
--boundary
Content-Disposition: form-data; name="startTime"

12:00:00
--boundary
Content-Disposition: form-data; name="endTime"

13:00:00
--boundary
Content-Disposition: form-data; name="adultCount"

5
--boundary
Content-Disposition: form-data; name="totalPrice"

120000
--boundary--


###
# Rooftop Seach Cond 조회
GET {{host}}/api/v1/rooftops/search?page=0&minPrice=0&maxPrice=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# 본인 RooftopReview 조회
GET {{host}}/api/v1/rooftops/reviews?page=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Rooftop Review 생성
POST {{host}}/api/v1/rooftops/reviews/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "grade": 5,
  "content": "test 용도입니다..."
}

###
# Rooftop Review 삭제
DELETE {{host}}/api/v1/rooftops/reviews/1/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json