# 로그인
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "gwangin1999@naver.com",
  "password": "qorrhkddls1!"
}

> {%
client.global.set("accessToken", response.body.data.tokenDto.accessToken);
client.global.set("refreshToken", response.body.data.tokenDto.refreshToken);
 %}

###
# 로그아웃
DELETE {{host}}/api/v1/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# AccessToken 재발급
GET {{host}}/api/v1/auth/2/check-refresh-token
refresh-token: {{refreshToken}}
Content-Type: application/json

> {%
client.global.set("accessToken", response.body.data.tokenDto.accessToken);
client.global.set("refreshToken", response.body.data.tokenDto.refreshToken);
 %}