jwt:
  type: Bearer
  expirationTime: ENC(w0xGa4flVsuC6k9WEWRbUA==)
  refreshExpirationTime: ENC(b9+5QUqFPMnbE6syP1WeTNI+vxUbz3pF)
  secret: ENC(pb6gyYS0DjANthAVHg5EntIALTx6d2vj3yOn43g3qP74lBw5DbqmC+khZ7bLaE4fFGYfwSU9F7qFvM5MqqycS7zI4lNPvVuyzUSo/CEMzOPOEHI1bpM/Dg==)

spring:
  datasource:
    url: ENC(NKs2bLAkootOKvoVj1uY4wRtsjrv2nz9CMbKdqywwsGRQsiRZzvrOK6Zm8rZdlQOZBq+iqRX4qGMxYFRkqnS8OoVD9KFXLyDCn3yOSOv8mMYH6jt660HWzJUpKjsg5l+K7B9t33iVUDd13LxLelNh4lpINTZAmWmncrgYAY9V4fZpl4jyOZO5Vvw7U0Q+athzqYXukLEPXU=)
    username: ENC(K60D91hdXcieW34hermt/A==)
    password: ENC(zbx+JjmiRVVQTt43yFfo5CkuhUGma2xn)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(JDM2lYsRyxC0CQKw9zMAL2vTME1qsiMzQ5GD7R9M1cfsfqrMx8VS7Q==)
    password: ENC(pQwra588CqRw5YyIWy5vjdthqj0WTv/U)
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
