jwt:
  type: Bearer
  expirationTime: ENC(w0xGa4flVsuC6k9WEWRbUA==)
  refreshExpirationTime: ENC(b9+5QUqFPMnbE6syP1WeTNI+vxUbz3pF)
  secret: ENC(pb6gyYS0DjANthAVHg5EntIALTx6d2vj3yOn43g3qP74lBw5DbqmC+khZ7bLaE4fFGYfwSU9F7qFvM5MqqycS7zI4lNPvVuyzUSo/CEMzOPOEHI1bpM/Dg==)

spring:
  datasource:
    url: ENC(NKs2bLAkootOKvoVj1uY4wRtsjrv2nz9CMbKdqywwsGRQsiRZzvrOK6Zm8rZdlQOZBq+iqRX4qGMxYFRkqnS8OoVD9KFXLyDCn3yOSOv8mMYH6jt660HWzJUpKjsg5l+K7B9t33iVUDd13LxLelNh4lpINTZAmWmncrgYAY9V4fZpl4jyOZO5Vvw7U0Q+athzqYXukLEPXU=)
    username: ENC(K60D91hdXcieW34hermt/A==)
    password: ENC(zbx+JjmiRVVQTt43yFfo5CkuhUGma2xn)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(JDM2lYsRyxC0CQKw9zMAL2vTME1qsiMzQ5GD7R9M1cfsfqrMx8VS7Q==)
    password: ENC(pQwra588CqRw5YyIWy5vjdthqj0WTv/U)
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
cloud:
  aws:
    credentials:
      access-key: ENC(6fFyx2upkFaJBIAB51jlD/1gLZu3ppK+5qEf9GrI0jA=)
      secret-key: ENC(sV2knPVjuXOY3ZKcxzeY8Crk7SR9z0a83BOdEzsaCW/RU7E2YQ4SGbeqJCb7AGFUG+wxePLX50E=)
    s3:
      bucket: ENC(jLChXcA4renjdJWttKztl/sCPQB7WCZBYRz8DRAB7aQ=)
    stack:
      auto: false
    region:
      static: ap-northeast-2

file:
  dir: ENC(UyKSbTtlgAK6xY80dSkCR3MqwMiKID1D)

