jwt:
  type: Bearer
  expirationTime: ENC(w0xGa4flVsuC6k9WEWRbUA==)
  refreshExpirationTime: ENC(b9+5QUqFPMnbE6syP1WeTNI+vxUbz3pF)
  secret: ENC(pb6gyYS0DjANthAVHg5EntIALTx6d2vj3yOn43g3qP74lBw5DbqmC+khZ7bLaE4fFGYfwSU9F7qFvM5MqqycS7zI4lNPvVuyzUSo/CEMzOPOEHI1bpM/Dg==)

spring:
  datasource:
    url: ENC(NKs2bLAkootOKvoVj1uY4wRtsjrv2nz9CMbKdqywwsGRQsiRZzvrOK6Zm8rZdlQOZBq+iqRX4qGMxYFRkqnS8OoVD9KFXLyDCn3yOSOv8mMYH6jt660HWzJUpKjsg5l+K7B9t33iVUDd13LxLelNh4lpINTZAmWmncrgYAY9V4fZpl4jyOZO5Vvw7U0Q+athzqYXukLEPXU=)
    username: ENC(K60D91hdXcieW34hermt/A==)
    password: ENC(zbx+JjmiRVVQTt43yFfo5CkuhUGma2xn)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(JDM2lYsRyxC0CQKw9zMAL2vTME1qsiMzQ5GD7R9M1cfsfqrMx8VS7Q==)
    password: ENC(pQwra588CqRw5YyIWy5vjdthqj0WTv/U)
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  redis:
    host: ENC(qA9e/xixLQY926CWKXhUdV9EU2AjmMSb)

cloud:
  aws:
    credentials:
      access-key: ENC(6fFyx2upkFaJBIAB51jlD/1gLZu3ppK+5qEf9GrI0jA=)
      secret-key: ENC(sV2knPVjuXOY3ZKcxzeY8Crk7SR9z0a83BOdEzsaCW/RU7E2YQ4SGbeqJCb7AGFUG+wxePLX50E=)
    s3:
      bucket: ENC(jLChXcA4renjdJWttKztl/sCPQB7WCZBYRz8DRAB7aQ=)
    stack:
      auto: false
    region:
      static: ap-northeast-2

file:
  dir: ENC(UyKSbTtlgAK6xY80dSkCR3MqwMiKID1D)

oauth2:
  kakao:
    get_token_uri: ENC(BDIuqjILFWFsQXKyHVon/xdlwVuv1iBzpq9tZb+Gnh+6A0/tovrefi3yTdlDcnGQ)
    user_info_uri: ENC(KsMsD93IfD4tSTQ0PlwHl5gmg9fUo6pYZNEZ2HHhzwWsAhkSWL70yINwHeUc5C8z)
    client_id: ENC(7mvEKM64dXCfGImTc22ENf6BcHPnnLPtrjmKrqrJTjuS0b1m3QnP9sqO1bIFj9BE)
    client_secret: ENC(xTkFF5wK5K1TwcE70i62waZ8GB2/z+jBRP9ppX22gSNgF/lQyuc6TIEVlYPLcyPe)
    redirect_url: ENC(2JX8hefQ25azbkWny28QoTu0rAIu1olEQuRdHww5hFoUucivPfqsxqygyc0PFETbaY5Nqqczyl9TA7zapd+CYve+5h5QKEPHw/ina540AHzC/+Md7kSsuoETJqIZbXeg)

  naver:
    get_token_uri: ENC(1CTP4r4OP7aZ44e8y+ht3GMZo+IG4PxxF1PYDIJ67ZGlf+031Q5uQkuhjpzdyFSZ)
    user_info_uri: ENC(DkqCAs7+PZvrKlOHQyzPVvEwPOv1ZFyPFpUzajJHGF3etDjbAPUx8nqQ/4dLlzER)
    client_id: ENC(SZ4ndXday0Iq8ZkrWo0XQqJXbIn38gHhYY4mWNfgnVI=)
    client_secret: ENC(cNaGIoW2QPFErwOAjTI3iR2/VplgqP3t)
    redirect_url: ENC(cdOYVHcSbX4xg4zkHcWYKKMCFiPDWri/kRS3gSrLOGxeNAY1D7ar348UkBbdoiKZvQ9K4vOkynvlFme7shFNeypZuyKQomBP1ZMeYsTGWIlXnW69vrf1fOYiIEWmQlpY)

  google:
    get_token_uri: ENC(MYFeEnUIYxifV5miyUPGNgCPZSHZsIsh10zOjRboulTdbqnjb3N+ISSp7gnDZwga)
    user_info_uri: ENC(lQpSISjgACmCsuhd8UxpAKS2z5PAiHQnPSKAXjHVmPuZXuN3p1Y187nC1y2OdqT8+2Q28wqtvEw=)
    client_id: ENC(jacEGsHNuh0Dz4a6cNl7/XRfJkN0YNGzVsD8EN+oNISMoEkdebHyCYwJTZ77OteIgU+ezrCGFygbQ0Vcah9JJJzAdckTUbzv1v7mfLheBGs=)
    client_secret: ENC(525pw4H28+G4ytsYHBerP0QI1Ovzs3RMAY0m3N3d/pl5qlx2fzvn2J29brz159XB)
    redirect_url: ENC(L2CYB3QvW15bQmRmvBwtZHZk3eI3tgE8QHS+9MS9SUiQCXK9y1VtwwNFBOnDHpwWcItt904kDYZ1t5uigJQrJr02JJyeWrvx7JIQMQyES592ZdTyRlNW0MAgLncH4oLe)